name: typing
on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: python -m pip install uv

      - name: Install dependencies
        run: |
          uv sync --frozen --extra dev
          pip install --upgrade --only-binary=:all: "mypy[faster-cache]>=1.13"

      - uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml', '**/*.py') }}
          restore-keys: ${{ runner.os }}-mypy-

      - name: Type check
        run: mypy -p anml_exp -j 0
